/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as erc20VotesSol from "./ERC20Votes.sol";
export type { erc20VotesSol };
import type * as myErc721Sol from "./MyERC721.sol";
export type { myErc721Sol };
import type * as tokenSaleSol from "./TokenSale.sol";
export type { tokenSaleSol };
import type * as tokenizedBallotSol from "./TokenizedBallot.sol";
export type { tokenizedBallotSol };
