/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export * as erc20VotesSol from "./ERC20Votes.sol";
export * as myErc721Sol from "./MyERC721.sol";
export * as tokenSaleSol from "./TokenSale.sol";
export * as tokenizedBallotSol from "./TokenizedBallot.sol";
