/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMyERC20Token } from "./IMyERC20Token";
export type { IMyERC721Token } from "./IMyERC721Token";
export type { TokenSale } from "./TokenSale";
